### ISSUE TITLE
Python 3 support required by end of this year

### ISSUE THREAD

**Issue by andyburras** [cta-wave/WMAS#54]
The requirements give "Python 2.7+ (but not Python 3.x)" and our own experiments bear this out.
However, Python 2 support officially ceases on January 1, 2020 so running under Python3 is required

**Comment by squapp** [comment]
this is a dependency of the [W3C Web Platform Tests ](https://github.com/web-platform-tests/wpt). I expect Python 3 will be supported with an update to the latest W3C WPT later this year

**Comment by JohnRiv** [comment]
Looks like based on https://github.com/web-platform-tests/wpt/issues/8820 and https://github.com/web-platform-tests/wpt/issues/10128 that WPT won't be fully on Python 3 anytime soon. 

When the time comes that WPT is fully on Python 3, I assume we would just import the latest from them, so I'd lean towards closing this issue rather than leave it open for a long time.

**Comment by JohnRiv** [comment]
On the 12/11/19 HATF call, we agreed to close this
