### ISSUE TITLE
test runner / deployment: HbbTV / Smart TV friendly landing page

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/WMAS#61]
The landing page used in WMAS (and re-used in DPCTF) is not very HbbTV friendly and probably not very friendly towards Smart TVs in general.

It would be good to have a more Smart TV / HbbTV friendly landing page.

It may be more appropriate to have two pages;
- a generic Smart TV friendly page applicable to both ATSC3 and HbbTV (and others) 
- an HbbTV specific page including HbbTV-specific API calls that can be launched as an HbbTV broadcast related application and will transition to broadcast-independent if launched from broadcast signalling.

**Comment by jpiesing** [comment]
This issue may turn into nothing if the test engineer would never need to interact with this page on a device under test.

**Comment by louaybassbouss** [comment]
@jpiesing the landing page now includes a javascript lib (hbbtv.js) which checks via the User Agent if the test runs on HbbTV terminal and if yes, it do the additional initialisations required for HbbTV.

**Comment by JohnRiv** [comment]
HATF March 2nd update - @louaybassbouss will provide a screencast of the test set up

**Comment by yanj-github** [comment]
@louaybassbouss and @jpiesing correct me please if I am wrong. 
On the TR individual test always starts with pre-test.html before it goest to actual test HTML+JS.
pre-test.html shows QR code that is used by OF to scan and determine the start of test and also which test is running. 
If HbbTV specific API calls made and broadcast to start test I guess it needs to show pre-test page to make a start.
Do we need to to make the pre-test page HbbTV / Smart TV friendly so that the TV can lands on this page?

**Comment by yanj-github** [comment]
@louaybassbouss I think we would like to have a javascript lib (hbbtv.js) included for all the pages that the Device Under Test needs to serve as part of running the WMAS tests and DPCTF tests please? HTML pages that should be on companion device are not required.

**Comment by FritzHeiden** [comment]
@yanj-github hbbtv.js is now included in all HTML files.

**Comment by yanj-github** [comment]
@louaybassbouss Yes indeed, I understand this involve in changing thousands of files. 
The issue I have is, I am creating a test session and start a test via API calls, and trying to broahcast DUT to land on a page to run the test session. This will be a first test url which cannot launched from HbbTV broadcast signalling without having hbbtv.js. 

Is it eaiser to have a HbbTV-specific landing page (already bind the session tocken) instead of standard index.html? Something like "https://webapitests2019.ctawave.org/wave/index.html?token=xxxxxxx"
I also noticed "https://webapitests2019.ctawave.org/wave/newsession.html?token=xxxxxxx" Which we might be able to use, But if I start test elsewhere (not on DUT) newsession.html not direct to correct test url.

**Comment by FritzHeiden** [comment]
@yanj-github You can use /wave/next.html?token=xxxx to execute the next test in the session. However, hbbtv.js is still required to be added to next.html

**Comment by yanj-github** [comment]
Thanks @FritzHeiden I just checked the DPCTF tests, by landing on /wave/next.html?token=xxxx which works fine. 
Can you help to add hbbtv.js to next.html for WMAS tests please?

**Comment by FritzHeiden** [comment]
@yanj-github I added the hbbtv.js to next.html and added another query parameter "delay", which will delay the test execution by the provided value in ms. This may help if the redirection to the test is faster than hbbtv takes to initialize.

**Comment by yanj-github** [comment]
@FritzHeiden Can you provide information of where I can set this "delay" please?
Currently next.html redirected so quicky so that DUT cannot land on this page.

**Comment by louaybassbouss** [comment]
> @FritzHeiden Can you provide information of where I can set this "delay" please? Currently next.html redirected so quicky so that DUT cannot land on this page.

@yanj-github  this is an example https://webapitests2019.ctawave.org/wave/index.html?token=xxxxxxx&delay=3000 . This will delay the redirection for 3s.

**Comment by yanj-github** [comment]
Thanks @louaybassbouss I just tried with one test this is working fine.

**Comment by jpiesing** [comment]
Based on @yanj-github 's comment above, I'm OK to close this.
