### ISSUE TITLE
Different results between wpt live and wmas tests

### ISSUE THREAD

**Issue by aajselamaslak** [cta-wave/WMAS#87]
When I execute some of the tests from wpt.live on chrome 120 vs tests from webapitests2023.ctawave.org I get different results:

https://wpt.live/content-security-policy/gen/top.http-rp/worker-src-self/sharedworker-classic.https.html
all tests are passing

https://webapitests2023.ctawave.org/content-security-policy/gen/top.http-rp/worker-src-self/sharedworker-classic.https.html
two of the tests are failing.

**Comment by FritzHeiden** [comment]
Thanks for reporting, will investigate

**Comment by louaybassbouss** [comment]
@aajselamaslak  webapitests2023.ctawave.org points currently to an older version of WMAS (WMAS2021). This is a temporary solution until the WMAS2023 Test Suit is deployed.  This is why you cannot compare the results, since wpt.live use the last version of the tests and WMAS uses the version from 2021. Once WMAS2023 Test Suite is deployed, we will repeat the test and make sure that both produce the same results. If this is not the case, we will deeper investigation.

**Comment by aajselamaslak** [comment]
Thank you for the reply.

**Comment by FritzHeiden** [comment]
As @louaybassbouss already explained, webapitests2023.ctawave.org still points to an older version. From the error message you can see that it fails because it tries to access a resource at webapitests2020.ctawave.org, which doesn't work due to cross origin restrictions. If I change the host name all tests pass as expected: 

https://webapitests2020.ctawave.org:8443/content-security-policy/gen/top.http-rp/worker-src-self/sharedworker-classic.https.html

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden .  @aajselamaslak  as you can see, even with older version of WMAS the tests Pass. If you think your question is answered, feel free to close this issue.

**Comment by aajselamaslak** [comment]
Thanks for your reply, yes it does.
